const $=s=>document.querySelector(s);
function toggleMenu(){$('#drawer').classList.toggle('show')} function closeTool(){$('#modal').classList.remove('show')}
function openTool(t){const titles={swg:'SWG Wire Weight Calculator',convert:'MM ↔ Inch Converter',bearing:'Bearing Number Finder',tap:'Tap Drill Size Calculator',thread:'Thread / TPI Converter',weight:'Material Weight Calculator'};let body='';
if(t==='convert') body=`<h2>${titles[t]}</h2><p class="sub">Quick metric ↔ imperial conversion.</p><div class="field"><label>VALUE</label><input id="cv" type="number" step="any" placeholder="25.4"></div><div class="field"><label>FROM</label><select id="from"><option>mm</option><option>inch</option></select></div><button class="calc-btn" onclick="convert()">CONVERT</button><div class="result" id="r">Result will appear here.</div>`;
else if(t==='bearing') body=`<h2>${titles[t]}</h2><p class="sub">ID + OD + width gives a much more reliable match.</p><div class="form-grid"><div class="field"><label>ID (MM)</label><input id="bid" type="number" step="any" placeholder="20"></div><div class="field"><label>OD (MM)</label><input id="bod" type="number" step="any" placeholder="47"></div></div><div class="field"><label>WIDTH (MM)</label><input id="bw" type="number" step="any" placeholder="14"></div><button class="calc-btn" onclick="bearing()">FIND BEARING</button><div class="result" id="r">Example: 20 × 47 × 14 → likely 6204.</div>`;
else if(t==='tap') body=`<h2>${titles[t]}</h2><p class="sub">Verified thread tables will be expanded in the next build.</p><div class="field"><label>THREAD</label><input id="th" placeholder="M10 x 1.5 / 1/4-20 UNC / 1/4 BSW"></div><button class="calc-btn" onclick="tap()">GET DRILL SIZE</button><div class="result" id="r">Recommended drill will appear here.</div>`;
else if(t==='thread') body=`<h2>${titles[t]}</h2><p class="sub">Convert thread pitch and TPI.</p><div class="field"><label>VALUE</label><input id="tv" type="number" step="any" placeholder="20"></div><div class="field"><label>FROM</label><select id="tf"><option>TPI</option><option>mm pitch</option></select></div><button class="calc-btn" onclick="thread()">CONVERT</button><div class="result" id="r">Result will appear here.</div>`;
else if(t==='weight') body=`<h2>${titles[t]}</h2><p class="sub">Simple density-based material weight estimate.</p><div class="form-grid"><div class="field"><label>VOLUME (cm³)</label><input id="vol" type="number" step="any" placeholder="100"></div><div class="field"><label>DENSITY (g/cm³)</label><input id="den" type="number" step="any" value="7.85"></div></div><button class="calc-btn" onclick="weight()">CALCULATE</button><div class="result" id="r">Result will appear here.</div>`;
else body=`<h2>${titles[t]}</h2><p class="sub">Weight unit is kilograms (kg).</p><div class="field"><label>SWG COMBINATION</label><input id="swg" value="18+18+19"></div><div class="field"><label>TOTAL WEIGHT (kg)</label><input id="swgw" type="number" step="any" placeholder="10"></div><button class="calc-btn" onclick="swgCalc()">CALCULATE</button><div class="result" id="r">Enter the combination and total weight.</div>`;
$('#toolContent').innerHTML=body;$('#modal').classList.add('show')}
function convert(){let v=+$('#cv').value;if(!Number.isFinite(v))return $('#r').innerHTML='Enter a value';$('#r').innerHTML=$('#from').value==='mm'?`Inch<strong>${(v/25.4).toFixed(5)}"</strong>`:`MM<strong>${(v*25.4).toFixed(4)} mm</strong>`}
function bearing(){let id=+$('#bid').value,od=+$('#bod').value,w=+$('#bw').value;$('#r').innerHTML=(id===20&&od===47&&w===14)?`Likely bearing<strong>6204</strong>`:`Entered size<strong>${id||'—'} × ${od||'—'} × ${w||'—'} mm</strong>`}
function tap(){let x=$('#th').value.toUpperCase().replace(/\s/g,'');let ans=x.includes('M10')?'8.5 mm':x.includes('M8')?'6.8 mm':x.includes('M6')?'5.0 mm':x.includes('1/4-20')?'5.1 mm':'Use the verified thread table';$('#r').innerHTML=`Recommended drill<strong>${ans}</strong>`}
function thread(){let v=+$('#tv').value;if(!(v>0))return $('#r').innerHTML='Enter a positive value';$('#r').innerHTML=$('#tf').value==='TPI'?`Pitch<strong>${(25.4/v).toFixed(4)} mm</strong>`:`TPI<strong>${(25.4/v).toFixed(3)} TPI</strong>`}
function weight(){let m=+$('#vol').value*+$('#den').value;if(!Number.isFinite(m))return $('#r').innerHTML='Enter volume and density';$('#r').innerHTML=`Approx. weight<strong>${m.toFixed(1)} g</strong>`}
function swgCalc(){const combo=$('#swg').value.trim().split('+').map(x=>x.trim()).filter(Boolean);const total=+$('#swgw').value;if(!combo.length||!(total>0))return $('#r').innerHTML='Enter SWG combination and total kg';const dia={18:1.219,19:1.067,20:0.914,21:0.813,22:0.711,23:0.610,24:0.559,25:0.508,26:0.457};const areas=combo.map(x=>Math.PI*Math.pow((dia[x]||0)/2,2));if(areas.some(x=>!x))return $('#r').innerHTML='SWG data not available for one or more sizes';const sum=areas.reduce((a,b)=>a+b,0);const vals=areas.map(a=>total*a/sum);$('#r').innerHTML=vals.map((v,i)=>`SWG ${combo[i]}<strong>${v.toFixed(4)} kg</strong>`).join('')+`<hr><b>Total<strong>${vals.reduce((a,b)=>a+b,0).toFixed(4)} kg</strong></b>`}
function filterTools(t){document.querySelectorAll('.tool-card').forEach(x=>x.style.display=(t==='all'||x.dataset.tool===t)?'block':'none')}
